name: Publish npmjs Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-py3.9-${{ hashFiles('.github/workflows/npm-publish.yml') }}
      - name: Install Python dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pre-commit
      - run: make release-npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_API_TOKEN}}
